# Generated by Django 6.0.3 on 2026-04-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='phone')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'created_at'], name='accounts_ot_phone_463bcb_idx')],
            },
        ),
    ]
