# Generated by Django 6.0 on 2026-05-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0008_restaurant_whatsapp_feedback_template"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="expires at"),
        ),
        migrations.AddField(
            model_name="otp",
            name="is_used",
            field=models.BooleanField(default=False, verbose_name="used"),
        ),
        migrations.AddField(
            model_name="otp",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to="restaurants.restaurant",
                verbose_name="restaurant",
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(fields=["restaurant", "phone", "created_at"], name="accounts_ot_restau_27fb70_idx"),
        ),
    ]
