# Generated by Django 6.0.3 on 2026-05-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_sms_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otp',
            new_name='accounts_ot_restaur_11e740_idx',
            old_name='accounts_ot_restau_27fb70_idx',
        ),
    ]
