# Generated by Django 6.0.3 on 2026-07-12 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0013_restaurant_scanner_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('welcome', 'Welcome'), ('checked_in', 'Checked In'), ('menu', 'Menu'), ('item_detail', 'Item Detail')], max_length=32, verbose_name='page key')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('schema_version', models.PositiveIntegerField(default=1, verbose_name='schema version')),
                ('layout', models.JSONField(blank=True, default=dict, verbose_name='layout')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_layouts', to='restaurants.restaurant', verbose_name='restaurant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_page_layouts', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'page layout',
                'verbose_name_plural': 'page layouts',
                'ordering': ['page_key'],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'page_key'), name='layouts_pagelayout_restaurant_page_key_uniq')],
            },
        ),
    ]
