# Generated by Django 6.0.3 on 2026-07-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layouts', '0001_initial_pagelayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelayout',
            name='schema_version',
            field=models.PositiveIntegerField(default=2, verbose_name='schema version'),
        ),
    ]
