# Generated by Django 6.0

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0002_campaignsend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignsend",
            name="target_type",
            field=models.CharField(max_length=32, verbose_name="target type"),
        ),
    ]
