# Generated by Django 6.0.3 on 2026-07-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignsend_lifecycle_and_recipient_events'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaignrecipientevent',
            new_name='campaigns_c_campaig_84f3cd_idx',
            old_name='campaigns_ca_campaign_c54fe0_idx',
        ),
        migrations.RenameIndex(
            model_name='campaignrecipientevent',
            new_name='campaigns_c_campaig_8099f9_idx',
            old_name='campaigns_ca_campaign_2ec7fd_idx',
        ),
    ]
