import type { ComponentType } from "react";
import {
  BannerRender,
  CategoryTabsRender,
  CheckInFormRender,
  CTAButtonRender,
  DividerRender,
  ItemDescriptionRender,
  ItemDetailShellRender,
  ItemImageRender,
  ItemPriceRender,
  LoyaltySummaryRender,
  MenuBookRender,
  MenuItemGridRender,
  PageRootRender,
  RestaurantLogoRender,
  RestaurantNameRender,
  SearchBarRender,
  TagsRender,
  TextRender,
} from "./components";
import type {
  LayoutComponentDef,
  LayoutRenderProps,
  PageKey,
} from "./types";

type RenderFn = ComponentType<LayoutRenderProps & { children?: React.ReactNode }>;

export const COMPONENT_REGISTRY: Record<string, LayoutComponentDef & { Render: RenderFn }> = {
  PageRoot: {
    type: "PageRoot",
    label: "Page",
    category: "layout",
    defaultProps: { padding: 0, background: null },
    defaultFrame: { x: 0, y: 0, w: 100, h: 100 },
    Render: PageRootRender,
  },
  RestaurantLogo: {
    type: "RestaurantLogo",
    label: "Restaurant Logo",
    category: "brand",
    defaultProps: { size: "md", align: "center" },
    defaultFrame: { x: 35, y: 8, w: 30, h: null },
    Render: RestaurantLogoRender,
  },
  RestaurantName: {
    type: "RestaurantName",
    label: "Restaurant Name",
    category: "brand",
    defaultProps: { align: "center", showTagline: true },
    defaultFrame: { x: 8, y: 12, w: 84, h: null },
    Render: RestaurantNameRender,
  },
  Text: {
    type: "Text",
    label: "Text",
    category: "layout",
    defaultProps: { text: "New text", align: "left", variant: "body" },
    defaultFrame: { x: 8, y: 20, w: 84, h: null },
    Render: TextRender,
  },
  Banner: {
    type: "Banner",
    label: "Banner",
    category: "media",
    defaultProps: { text: "Promotional banner", background: null },
    defaultFrame: { x: 4, y: 4, w: 92, h: null },
    Render: BannerRender,
  },
  Divider: {
    type: "Divider",
    label: "Divider",
    category: "layout",
    defaultProps: {},
    defaultFrame: { x: 10, y: 40, w: 80, h: null },
    Render: DividerRender,
  },
  SearchBar: {
    type: "SearchBar",
    label: "Search Bar",
    category: "menu",
    pages: ["menu"],
    defaultProps: { placeholder: "Search menu…" },
    defaultFrame: { x: 4, y: 8, w: 92, h: null },
    Render: SearchBarRender,
  },
  CategoryTabs: {
    type: "CategoryTabs",
    label: "Categories",
    category: "menu",
    pages: ["menu"],
    defaultProps: { scrollable: true },
    defaultFrame: { x: 0, y: 16, w: 100, h: null },
    Render: CategoryTabsRender,
  },
  MenuBook: {
    type: "MenuBook",
    label: "Menu Book",
    category: "menu",
    pages: ["menu"],
    defaultProps: {},
    defaultFrame: { x: 0, y: 0, w: 100, h: 100 },
    Render: MenuBookRender,
  },
  MenuItemGrid: {
    type: "MenuItemGrid",
    label: "Menu Item Grid",
    category: "menu",
    pages: ["menu"],
    defaultProps: {
      columns: 2,
      direction: "grid",
      density: "comfortable",
      source: "active_category",
      maxItems: 5,
      order: "menu",
    },
    defaultStyle: { gap: 8 },
    defaultFrame: { x: 4, y: 24, w: 92, h: 60 },
    Render: MenuItemGridRender,
  },
  MenuItemCard: {
    type: "MenuItemCard",
    label: "Menu Item Card",
    category: "menu",
    pages: ["menu"],
    defaultProps: { density: "comfortable" },
    defaultFrame: { x: 10, y: 30, w: 80, h: null },
    Render: MenuItemGridRender,
  },
  ItemDetailShell: {
    type: "ItemDetailShell",
    label: "Item Detail Shell",
    category: "menu",
    pages: ["item_detail"],
    defaultProps: {},
    defaultFrame: { x: 0, y: 0, w: 100, h: 100 },
    Render: ItemDetailShellRender,
  },
  ItemImage: {
    type: "ItemImage",
    label: "Item Image",
    category: "menu",
    pages: ["item_detail"],
    defaultProps: { aspect: "square", width: "full" },
    defaultFrame: { x: 5, y: 5, w: 90, h: 40 },
    Render: ItemImageRender,
  },
  ItemDescription: {
    type: "ItemDescription",
    label: "Item Description",
    category: "menu",
    pages: ["item_detail"],
    defaultProps: { align: "left" },
    defaultFrame: { x: 5, y: 60, w: 90, h: null },
    Render: ItemDescriptionRender,
  },
  ItemPrice: {
    type: "ItemPrice",
    label: "Item Price",
    category: "menu",
    pages: ["item_detail"],
    defaultProps: { align: "left" },
    defaultFrame: { x: 5, y: 52, w: 90, h: null },
    Render: ItemPriceRender,
  },
  Tags: {
    type: "Tags",
    label: "Tags",
    category: "menu",
    pages: ["item_detail", "menu"],
    defaultProps: { showAll: true },
    defaultFrame: { x: 5, y: 48, w: 90, h: null },
    Render: TagsRender,
  },
  CTAButton: {
    type: "CTAButton",
    label: "CTA Button",
    category: "form",
    defaultProps: {
      label: "Continue",
      action: "navigate_menu",
      variant: "primary",
      width: "full",
    },
    defaultFrame: { x: 6, y: 80, w: 88, h: null },
    Render: CTAButtonRender,
  },
  CheckInForm: {
    type: "CheckInForm",
    label: "Check-In Form",
    category: "form",
    pages: ["welcome"],
    defaultProps: { showName: true, showPhone: true },
    defaultFrame: { x: 6, y: 36, w: 88, h: null },
    Render: CheckInFormRender,
  },
  LoyaltySummary: {
    type: "LoyaltySummary",
    label: "Loyalty Summary",
    category: "form",
    pages: ["checked_in"],
    defaultProps: { visitGoal: 5, showProgressBar: true },
    defaultFrame: { x: 6, y: 28, w: 88, h: null },
    Render: LoyaltySummaryRender,
  },
};

export function toolboxForPage(pageKey: PageKey): (LayoutComponentDef & { Render: RenderFn })[] {
  return Object.values(COMPONENT_REGISTRY).filter(
    (def) => def.type !== "PageRoot" && (!def.pages || def.pages.includes(pageKey)),
  );
}

export function getComponent(type: string) {
  return COMPONENT_REGISTRY[type];
}
