# Generated by Django 6.0.3 on 2026-04-07 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone', models.CharField(max_length=32, verbose_name='phone')),
                ('total_visits', models.PositiveIntegerField(default=0, verbose_name='total visits')),
                ('last_visit', models.DateTimeField(blank=True, null=True, verbose_name='last visit')),
                ('tag', models.CharField(choices=[('vip', 'VIP'), ('frequent', 'Frequent'), ('first_time', 'First time'), ('regular', 'Regular')], default='first_time', max_length=32, verbose_name='tag')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='restaurants.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True, verbose_name='visit time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='customers.customer', verbose_name='customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='restaurants.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'visit',
                'verbose_name_plural': 'visits',
                'ordering': ['-visit_time'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['restaurant', 'phone'], name='customers_c_restaur_216783_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('restaurant', 'phone'), name='customers_unique_phone_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['restaurant', 'visit_time'], name='customers_v_restaur_4de7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['customer', 'visit_time'], name='customers_v_custome_595d65_idx'),
        ),
    ]
