# Generated by Django 6.0

from django.db import migrations
from django.db import models


def forwards_migrate_regular(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")
    Customer.objects.filter(tag="regular").update(tag="neutral")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_customer_notes"),
    ]

    operations = [
        migrations.RunPython(forwards_migrate_regular, noop_reverse),
        migrations.AlterField(
            model_name="customer",
            name="tag",
            field=models.CharField(
                choices=[
                    ("vip", "VIP"),
                    ("frequent", "Frequent"),
                    ("first_time", "First time"),
                    ("neutral", "Neutral"),
                    ("inactive", "Inactive"),
                ],
                default="first_time",
                max_length=32,
                verbose_name="tag",
            ),
        ),
    ]
