# Generated by Django 6.0 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_customertag_neutral_inactive"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="otp_verified_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="otp verified at"),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_verified",
            field=models.BooleanField(default=False, verbose_name="phone verified"),
        ),
    ]
