# Generated by Django 6.0.3 on 2026-04-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('location', models.TextField(blank=True, verbose_name='location')),
                ('whatsapp_number', models.CharField(blank=True, max_length=32, verbose_name='WhatsApp number')),
                ('whatsapp_api_token', models.TextField(blank=True, verbose_name='WhatsApp API token')),
                ('whatsapp_phone_number_id', models.CharField(blank=True, max_length=64, verbose_name='WhatsApp phone number ID')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'ordering': ['name'],
            },
        ),
    ]
