# Generated by Django 6.0.3 on 2026-04-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='google_review_link',
            field=models.URLField(blank=True, verbose_name='Google review link'),
        ),
    ]
