# Generated by Django 6.0.3 on 2026-04-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_google_review_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, help_text='Must match the Cloud API Phone number ID for this business (same value as WHATSAPP_PHONE_NUMBER_ID in env). Required for inbound feedback webhooks to resolve this restaurant.', max_length=64, verbose_name='WhatsApp phone number ID'),
        ),
    ]
