# Generated by Django 6.0.3 on 2026-04-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_whatsapp_phone_number_id_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='WhatsApp phone number ID'),
        ),
    ]
