# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0005_templates_membership_and_review_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="whatsapp_broadcast_template_language",
            field=models.CharField(
                blank=True,
                default="en",
                help_text="Template language code (e.g. en, en_US); must match Meta.",
                max_length=32,
                verbose_name="WhatsApp broadcast template language code",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="whatsapp_broadcast_template_name",
            field=models.CharField(
                blank=True,
                help_text="Meta-approved template name. Body must include one variable; campaign text fills {{1}}.",
                max_length=512,
                verbose_name="WhatsApp broadcast template name",
            ),
        ),
    ]
