# Generated by Django 6.0.3 on 2026-05-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_sms_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='whatsapp_otp_template_language',
            field=models.CharField(blank=True, default='en', help_text='Must match the OTP template language in WhatsApp Manager (e.g. en).', max_length=32, verbose_name='WhatsApp OTP template language code'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='whatsapp_otp_template_name',
            field=models.CharField(blank=True, help_text='Required for OTP outside the 24-hour session window: Meta template name; body must include {{1}} for the verification code.', max_length=512, verbose_name='WhatsApp OTP template name'),
        ),
    ]
