# Generated by Django 6.0.3 on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0011_automationrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="google_review_link",
            field=models.URLField(
                blank=True,
                max_length=2048,
                verbose_name="Google review link",
            ),
        ),
    ]
