# Generated by Django 6.0.3 on 2026-07-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_restaurant_design_tokens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='design_tokens',
        ),
    ]
