# Generated by Django 6.0.3 on 2026-05-05 22:48

import kotak.menu.image_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menuitem_is_jain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=kotak.menu.image_utils.menu_item_image_upload_to, verbose_name='image'),
        ),
    ]
